#![cfg(unix)]
//! The current request of a native Claude transcript is the latest prompt the
//! user submitted. Claude also writes `user` records the user never typed:
//! injected meta content, local command output, interrupt markers and task
//! notifications. Real sessions often end with one of these, and ranking one
//! would evaluate the wrong request.
use serde_json::{Value, json};
use std::path::PathBuf;
use std::process::Command;
use std::sync::atomic::{AtomicU64, Ordering};

static NEXT: AtomicU64 = AtomicU64::new(0);

// Intentionally retained: repository policy forbids automatic tree deletion.
fn workspace() -> PathBuf {
    let root = std::env::temp_dir().join(format!(
        "sr-transcript-request-{}-{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos(),
        NEXT.fetch_add(1, Ordering::Relaxed)
    ));
    for dir in ["workspace", "home", "config/sr"] {
        std::fs::create_dir_all(root.join(dir)).unwrap();
    }
    for name in ["alpha", "beta"] {
        let dir = root.join("workspace/.claude/skills").join(name);
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(
            dir.join("SKILL.md"),
            format!("---\ndescription: {name} helps with rust tests.\n---\nBody.\n"),
        )
        .unwrap();
    }
    root
}

fn record(n: usize, extra: Value, text: &str) -> String {
    let mut record = json!({"type": "user", "uuid": format!("u-{n}"),
                            "message": {"role": "user", "content": text}});
    record
        .as_object_mut()
        .unwrap()
        .extend(extra.as_object().unwrap().clone());
    record.to_string()
}

const PROMPT: &str = "The rust tests are failing; find and repair the failing test.";

#[test]
fn records_the_user_did_not_submit_never_become_the_request() {
    let root = workspace();
    let lines = [
        record(
            1,
            json!({"promptSource": "typed", "origin": {"kind": "human"}}),
            PROMPT,
        ),
        record(
            2,
            json!({"isMeta": true}),
            "Caveat: generated by local commands.",
        ),
        record(
            3,
            json!({}),
            "<local-command-stdout>Login successful</local-command-stdout>",
        ),
        record(4, json!({}), "[Request interrupted by user]"),
        record(
            5,
            json!({"origin": {"kind": "task-notification"}}),
            "A background task finished.",
        ),
    ];
    let transcript = root.join("workspace/session.jsonl");
    std::fs::write(&transcript, lines.join("\n") + "\n").unwrap();
    // A dry run previews the exact request without any network or state.
    let output = Command::new(env!("CARGO_BIN_EXE_sr"))
        .env_clear()
        .env("HOME", root.join("home"))
        .env("XDG_CONFIG_HOME", root.join("config"))
        .current_dir(root.join("workspace"))
        .args([
            "rank",
            "--transcript",
            transcript.to_str().unwrap(),
            "--harness",
            "claude_code",
            "--dry-run",
            "--json",
        ])
        .output()
        .unwrap();
    let value: Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(output.status.code(), Some(0), "{value}");
    let request: Value = serde_json::from_str(
        value["provider_request"]["stages"][0]["request"]
            .as_str()
            .unwrap(),
    )
    .unwrap();
    assert_eq!(request["state"]["latest_user_request"], PROMPT, "{request}");
}
